name: Run pre-commit

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libxkbcommon-dev
    - uses: pre-commit/action@v3.0.0

env:
  PIP_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2023-11-08
  UV_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2023-11-08
