name: Run pre-commit

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      pypi_wayback:
        image: ghcr.io/waleko/pypi-wayback
        ports:
        - 8629:8080
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libxkbcommon-dev
    - uses: pre-commit/action@v3.0.0

env:
  PIP_INDEX_URL: http://localhost:8629/2023-12-17
  UV_INDEX_URL: http://localhost:8629/2023-12-17
